name: blog
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cffi=2.0.0
  - clarabel=0.11.1
  - cvxpy=1.7.5
  - cvxpy-base=1.7.5
  - icu=78.2
  - joblib=1.5.3
  - libblas=3.11.0
  - libcblas=3.11.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libhwloc=2.12.2
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libmpdec=4.0.0
  - libosqp=1.0.0
  - libqdldl=0.1.8
  - libsqlite=3.51.2
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - mkl=2025.3.0
  - numpy=2.4.1
  - openssl=3.6.0
  - osqp=1.0.5
  - pip=25.3
  - pycparser=2.22
  - python=3.14.2
  - python_abi=3.14
  - qdldl-python=0.1.7.post5
  - scikit-learn=1.8.0
  - scipy=1.17.0
  - scs=3.2.11
  - setuptools=80.10.1
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - zstd=1.5.7
  - pip:
      - altair==6.0.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.4
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - idna==3.11
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - narwhals==2.15.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.1.0
      - protobuf==6.33.4
      - pyarrow==23.0.0
      - pydeck==0.9.1
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.53.0
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.4
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.3
      - watchdog==6.0.0
prefix: C:\Users\sambe\miniconda3\envs\blog
